### ISSUE TITLE
Completion for sub directories

### ISSUE THREAD

**Issue by jcubic** [edgorman/edgorman.github.io#43]
It seems that your completion works only for single level directories.

This don't work:
```
> cd about-me\so TAB
```

You can check my completion in GIT Web Terminal project, that project have real file system using BrowserFS that work with isomorphic git, but the completion should be implemented similarly with fake fs.

https://github.com/jcubic/git/blob/gh-pages/js/main.js#L1381

You can also have different completion for files and directories (in my terminal `cd` have different completion then `less` or `cat`).

**Comment by edgorman** [comment]
Fixed in latest commit.
